name: Proponer una idea / Feature request
description: Algo que te gustaría que AwayLock haga. / Something you'd like AwayLock to do.
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: ¿Qué te gustaría? / What would you like?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: ¿Para qué te serviría? / Why would it help?
